- name: docker build and push
  hosts: localhost

  tasks:
    - name: Build Image
      command: docker build -t testcalc.jar .
      args:
        chdir: /var/lib/jenkins/workspace/testing\ enviornment
    - name: Log in to Docker Hub
      community.docker.docker_login:
          registry_url: https://index.docker.io/v1/
          username: "tezaswa"
          password: "915368742@Awasthi"
    - name: push image
      command: docker push tezaswa/testcalc:latest
    - name: Pull Docker image from Docker Hub
      shell: docker pull tezaswa/testcalc:latest
