- name: docker build and push
  hosts: localhost

  tasks:
    - name: Build Image
      command: docker build -t testcalc.jar .
      args:
        chdir: /var/lib/jenkins/workspace/testing_enviornment
    - name: Log in to Docker Hub
      community.docker.docker_login:
          registry_url: https://index.docker.io/v1/
          username: "tezaswa2"
          password: "tezaswa@123"
    - name: tag image
      command: docker tag testcalc.jar tezaswa2/testcalc:latest
    - name: push image
      command: docker push tezaswa2/testcalc:latest
    - name: Pull Docker image from Docker Hub
      shell: docker pull tezaswa2/testcalc:latest
