- name: docker build and push
  hosts: localhost

  tasks:
    - name: push image
      command: docker push tezaswa/testcalc:latest
    - name: Pull Docker image from Docker Hub
      shell: docker pull tezaswa/testcalc:latest
