- name: docker build and push
  hosts: localhost

  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull tezaswa2/testcalc:latest
    - name: Run Docker container
      shell: docker run -d -p 8081:8080 tezaswa2/testcalc:latest